### ISSUE TITLE
dial udp 127.0.0.53:53: socket: too many open files

### ISSUE THREAD

**Issue by ddugovic** [dolegi/lichess-bot#5]
It appears a segmentation fault occurred... I didn't know that was possible in Go https://lichess.org/Gig0kNFp/black#17 :

```
May 31 04:49:45 vps178028 lichess-bot[16040]: Accepting challenge {HRGAQ7S6 created {chijss Chijss  2061 false true 2} {godelescherbot GodelEscherBot BOT 2474 false true 0} {atomic} true blitz white}
May 31 04:49:48 vps178028 lichess-bot[16040]: {gameFull Gig0kNFp true {atomic} {180000 2000} blitz startpos {gameState  180000 180000 2000 2000} {chijss} {godelescherbot}  0 0 0 0}
May 31 04:49:52 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 180000 180000 2000 2000}
May 31 04:50:01 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/f7f6
May 31 04:50:01 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 180000 180000 2000 2000}
May 31 04:50:05 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 178190 180000 2000 2000}
May 31 04:50:07 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/e7e6
May 31 04:50:07 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 178190 179480 2000 2000}
May 31 04:50:27 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 160270 179480 2000 2000}
May 31 04:50:31 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/c7c6
May 31 04:50:32 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 160260 177340 2000 2000}
May 31 04:50:39 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 155060 177340 2000 2000}
May 31 04:50:42 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/c6b5
May 31 04:50:42 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 155060 176020 2000 2000}
May 31 04:50:45 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 154480 176020 2000 2000}
May 31 04:50:47 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/g7g6
May 31 04:50:48 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 154470 175130 2000 2000}
May 31 04:50:48 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 156480 175120 2000 2000}
May 31 04:50:56 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/b8c6
May 31 04:50:57 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 156470 168570 2000 2000}
May 31 04:50:57 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 b5b6 158480 168560 2000 2000}
May 31 04:50:59 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/a7b6
May 31 04:50:59 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 b5b6 a7b6 158470 168100 2000 2000}
May 31 04:51:01 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 b5b6 a7b6 f1b5 159170 168090 2000 2000}
May 31 04:51:04 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/e8f7
May 31 04:51:04 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 b5b6 a7b6 f1b5 e8f7 159160 166410 2000 2000}
May 31 04:51:06 vps178028 lichess-bot[16040]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 c7c6 d4b5 c6b5 d1h5 g7g6 h5b5 b8c6 b5b6 a7b6 f1b5 e8f7 b5d7 159710 166400 2000 2000}
May 31 04:51:15 vps178028 lichess-bot[16040]: REQUEST bot/game/Gig0kNFp/move/a8a2
May 31 04:51:15 vps178028 lichess-bot[16040]: Failed request POST bot/game/Gig0kNFp/move/a8a2 Post https://lichess.org/api/bot/game/Gig0kNFp/move/a8a2: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
May 31 04:54:03 vps178028 lichess-bot[16040]: Accepting challenge {Gig0kNFp created {chijss Chijss  2072 false true 4} {godelescherbot GodelEscherBot BOT 2474 false true 0} {atomic} true blitz black}
May 31 04:54:06 vps178028 lichess-bot[16040]: Failed request GET bot/game/stream/DfI0p9kT Get https://lichess.org/api/bot/game/stream/DfI0p9kT: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
May 31 04:54:06 vps178028 lichess-bot[16040]: panic: runtime error: invalid memory address or nil pointer dereference
May 31 04:54:06 vps178028 lichess-bot[16040]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x68a7b0]
May 31 04:54:06 vps178028 lichess-bot[16040]: goroutine 1 [running]:
May 31 04:54:06 vps178028 lichess-bot[16040]: main.streamGame(0xc0032c5210, 0x8, 0xc0000523c0)
May 31 04:54:06 vps178028 lichess-bot[16040]:         /home/turing/lichess-bot/stream_game.go:46 +0xa0
May 31 04:54:06 vps178028 lichess-bot[16040]: main.handleEvent(0xc00352c000, 0xc0000523c0)
May 31 04:54:06 vps178028 lichess-bot[16040]:         /home/turing/lichess-bot/stream_event.go:75 +0x103
May 31 04:54:06 vps178028 lichess-bot[16040]: main.streamEvent(0xc0000523c0)
May 31 04:54:06 vps178028 lichess-bot[16040]:         /home/turing/lichess-bot/stream_event.go:59 +0x18c
May 31 04:54:06 vps178028 lichess-bot[16040]: main.main()
May 31 04:54:06 vps178028 lichess-bot[16040]:         /home/turing/lichess-bot/main.go:106 +0x591
```

**Comment by ddugovic** [comment]
Huh, and again https://lichess.org/b9A5G41Y#20 

```
Jun 01 20:32:17 vps178028 lichess-bot[2146]: Accepting challenge {b9A5G41Y created {xyzxyxz xyzxyxz  2342 true true 4} {godelescherbot GodelEscherBot BOT 2522 false true 0} {atomic} true bullet random}
Jun 01 20:32:20 vps178028 lichess-bot[2146]: {gameFull b9A5G41Y true {atomic} {30000 0} bullet startpos {gameState  30000 30000 0 0} {godelescherbot} {xyzxyxz}  0 0 0 0}
Jun 01 20:32:31 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/g1f3
Jun 01 20:32:31 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 30000 30000 0 0}
Jun 01 20:32:32 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 30000 30000 0 0}
Jun 01 20:32:32 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/e2e3
Jun 01 20:32:32 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 29750 30000 0 0}
Jun 01 20:32:33 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 29750 29610 0 0}
Jun 01 20:32:33 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/f3d4
Jun 01 20:32:33 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 29480 29610 0 0}
Jun 01 20:32:33 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 29480 29280 0 0}
Jun 01 20:32:33 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/d1h5
Jun 01 20:32:34 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 29240 29280 0 0}
Jun 01 20:32:34 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 29240 28960 0 0}
Jun 01 20:32:34 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/h5g5
Jun 01 20:32:34 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 29000 28950 0 0}
Jun 01 20:32:35 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 29000 28470 0 0}
Jun 01 20:32:35 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/d4b5
Jun 01 20:32:35 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 28760 28460 0 0}
Jun 01 20:32:36 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 28750 28470 0 0}
Jun 01 20:32:36 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/f2f3
Jun 01 20:32:36 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 28510 28460 0 0}
Jun 01 20:32:36 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 28500 28470 0 0}
Jun 01 20:32:36 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/f3e4
Jun 01 20:32:36 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 28260 28460 0 0}
Jun 01 20:32:37 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 a7a6 28250 28470 0 0}
Jun 01 20:32:37 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/b5c7
Jun 01 20:32:37 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 a7a6 b5c7 28010 28460 0 0}
Jun 01 20:32:37 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 a7a6 b5c7 f8d6 28000 28470 0 0}
Jun 01 20:32:37 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/g2g3
Jun 01 20:32:38 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 a7a6 b5c7 f8d6 g2g3 27770 28460 0 0}
Jun 01 20:32:38 vps178028 lichess-bot[2146]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 e2e3 e7e6 f3d4 f6f5 d1h5 g7g6 h5g5 d8g5 d4b5 g8f6 f2f3 f6e4 f3e4 a7a6 b5c7 f8d6 g2g3 f5f4 27760 28060 0 0}
Jun 01 20:32:38 vps178028 lichess-bot[2146]: REQUEST bot/game/b9A5G41Y/move/d2d3
Jun 01 20:32:38 vps178028 lichess-bot[2146]: Failed request POST bot/game/b9A5G41Y/move/d2d3 Post https://lichess.org/api/bot/game/b9A5G41Y/move/d2d3: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
Jun 01 20:33:10 vps178028 lichess-bot[2146]: Accepting challenge {b9A5G41Y created {xyzxyxz xyzxyxz  2368 true true 4} {godelescherbot GodelEscherBot BOT 2525 false true 0} {atomic} true bullet white}
Jun 01 20:33:14 vps178028 lichess-bot[2146]: Failed request GET bot/game/stream/zi8uI0PM Get https://lichess.org/api/bot/game/stream/zi8uI0PM: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
Jun 01 20:33:14 vps178028 lichess-bot[2146]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 01 20:33:14 vps178028 lichess-bot[2146]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x68a7b0]
Jun 01 20:33:14 vps178028 lichess-bot[2146]: goroutine 1 [running]:
Jun 01 20:33:14 vps178028 lichess-bot[2146]: main.streamGame(0xc003277f80, 0x8, 0xc0000523c0)
Jun 01 20:33:14 vps178028 lichess-bot[2146]:         /home/turing/lichess-bot/stream_game.go:46 +0xa0
Jun 01 20:33:14 vps178028 lichess-bot[2146]: main.handleEvent(0xc00315e480, 0xc0000523c0)
Jun 01 20:33:14 vps178028 lichess-bot[2146]:         /home/turing/lichess-bot/stream_event.go:75 +0x103
Jun 01 20:33:14 vps178028 lichess-bot[2146]: main.streamEvent(0xc0000523c0)
Jun 01 20:33:14 vps178028 lichess-bot[2146]:         /home/turing/lichess-bot/stream_event.go:59 +0x18c
Jun 01 20:33:14 vps178028 lichess-bot[2146]: main.main()
Jun 01 20:33:14 vps178028 lichess-bot[2146]:         /home/turing/lichess-bot/main.go:106 +0x591
```

**Comment by ddugovic** [comment]
Because I don't understand this, I'll have to switch to the Python-based BOT API:

```
Jun 04 00:27:38 vps178028 lichess-bot[21764]: Accepting challenge {DV763AK7 created {bull333 bull333  1919 true true 4} {godelescherbot GodelEscherBot BOT 2520 false true 0} {atomic} true bullet white}
Jun 04 00:27:42 vps178028 lichess-bot[21764]: {gameFull GqRMHbcn true {atomic} {30000 0} bullet startpos {gameState  30000 30000 0 0} {bull333} {godelescherbot}  0 0 0 0}
Jun 04 00:27:42 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 30000 30000 0 0}
Jun 04 00:27:42 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/f7f6
Jun 04 00:27:43 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 30000 30000 0 0}
Jun 04 00:27:43 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 29270 30000 0 0}
Jun 04 00:27:43 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/g8h6
Jun 04 00:27:44 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 29270 29740 0 0}
Jun 04 00:27:45 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 28470 29730 0 0}
Jun 04 00:27:45 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/c7c6
Jun 04 00:27:46 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 28460 29320 0 0}
Jun 04 00:27:47 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 27650 29320 0 0}
Jun 04 00:27:47 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/c6b5
Jun 04 00:27:47 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 27650 29060 0 0}
Jun 04 00:27:47 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 27650 29050 0 0}
Jun 04 00:27:47 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/e7e5
Jun 04 00:27:48 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 27650 28800 0 0}
Jun 04 00:27:49 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 c3b5 26710 28790 0 0}
Jun 04 00:27:49 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/d8a5
Jun 04 00:27:49 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 c3b5 d8a5 26700 28540 0 0}
Jun 04 00:27:51 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 c3b5 d8a5 b2b4 25310 28530 0 0}
Jun 04 00:27:51 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/a5a4
Jun 04 00:27:51 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 c3b5 d8a5 b2b4 a5a4 25300 28290 0 0}
Jun 04 00:27:53 vps178028 lichess-bot[21764]: {gameState  false {} {0 0}   {  0 0 0 0} {} {} g1f3 f7f6 f3d4 g8h6 h2h3 c7c6 d4b5 c6b5 b1c3 e7e5 c3b5 d8a5 b2b4 a5a4 e2e3 24050 28280 0 0}
Jun 04 00:27:53 vps178028 lichess-bot[21764]: REQUEST bot/game/GqRMHbcn/move/d7d5
Jun 04 00:27:53 vps178028 lichess-bot[21764]: Failed request POST bot/game/GqRMHbcn/move/d7d5 Post https://lichess.org/api/bot/game/GqRMHbcn/move/d7d5: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
Jun 04 00:28:25 vps178028 lichess-bot[21764]: Accepting challenge {GqRMHbcn created {bull333 bull333  2070 true true 4} {godelescherbot GodelEscherBot BOT 2520 false true 0} {atomic} true bullet black}
Jun 04 00:28:29 vps178028 lichess-bot[21764]: Failed request GET bot/game/stream/w3rmfIHn Get https://lichess.org/api/bot/game/stream/w3rmfIHn: dial tcp: lookup lichess.org on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files
Jun 04 00:28:29 vps178028 lichess-bot[21764]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 04 00:28:29 vps178028 lichess-bot[21764]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x68a7b0]
Jun 04 00:28:29 vps178028 lichess-bot[21764]: goroutine 1 [running]:
Jun 04 00:28:29 vps178028 lichess-bot[21764]: main.streamGame(0xc002f53b80, 0x8, 0xc0000523c0)
Jun 04 00:28:29 vps178028 lichess-bot[21764]:         /home/turing/lichess-bot/stream_game.go:46 +0xa0
Jun 04 00:28:29 vps178028 lichess-bot[21764]: main.handleEvent(0xc002e1ab40, 0xc0000523c0)
Jun 04 00:28:29 vps178028 lichess-bot[21764]:         /home/turing/lichess-bot/stream_event.go:75 +0x103
Jun 04 00:28:29 vps178028 lichess-bot[21764]: main.streamEvent(0xc0000523c0)
Jun 04 00:28:29 vps178028 lichess-bot[21764]:         /home/turing/lichess-bot/stream_event.go:59 +0x18c
Jun 04 00:28:29 vps178028 lichess-bot[21764]: main.main()
Jun 04 00:28:29 vps178028 lichess-bot[21764]:         /home/turing/lichess-bot/main.go:106 +0x591
Jun 04 00:28:29 vps178028 lichess-bot[4869]: {IRb2ipmU9lTdSWBX godelescherbot https://lichess.org/api/ {engines/stockfish {100 1 16 1000 /home/turing/lichess-bot/tb 6} {0 0 0}} {[antichess atomic chess960 crazyhouse fromPosition horde kingOfTheHill racingKings standard threeCheck] [ultraBullet bullet blitz rapid] [casual rated]} {0}}
```
